# Generated by Django 4.1 on 2022-08-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type_of_transaction',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], default='IN', max_length=3),
        ),
    ]
