# Generated by Django 4.1 on 2022-08-23 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_type_of_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='payment_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
